import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "run-sail",
    "add-your-app",
    "getting-started",
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
    {
      type: "category",
      label: "Packages",
      items: [
        {
          type: "category",
          label: "@finos/sail-desktop-agent",
          items: [{ type: "autogenerated", dirName: "packages/desktop-agent" }],
        },
        "packages/platform-api/overview",
        "packages/sail-web/overview",
        "packages/sail-electron/overview",
      ],
    },
    "development",
  ],
};

export default sidebars;
